# This is a basic workflow to help you get started with Actions

name: Add Don't merge label in ri branches

# Controls when the action will run. 
on:
  pull_request:
    branches:
    - "master"
    - "master-ri"
    - "dev-ri"
    - "unstable-ri"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.BAIKAL_CHECKOUT_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Don't merge']
            })
